//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNumismat2._0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNumismat2._0.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact available.
        /// </summary>
        internal static string _contactAvailable {
            get {
                return ResourceManager.GetString("_contactAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts available.
        /// </summary>
        internal static string _contactsAvailable {
            get {
                return ResourceManager.GetString("_contactsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Backup was successful.
        /// </summary>
        internal static string _dbBackup_BallonText {
            get {
                return ResourceManager.GetString("_dbBackup_BallonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup.
        /// </summary>
        internal static string _dbBackup_BalloonTitle {
            get {
                return ResourceManager.GetString("_dbBackup_BalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not run a Backup, since there is no Database file selected..
        /// </summary>
        internal static string _dbBackupNullReferenceExceptionText {
            get {
                return ResourceManager.GetString("_dbBackupNullReferenceExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string _dbBackupNullReferenceExceptionTitle {
            get {
                return ResourceManager.GetString("_dbBackupNullReferenceExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression of the Database was successful.
        /// </summary>
        internal static string _dbCompress_BallonText {
            get {
                return ResourceManager.GetString("_dbCompress_BallonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Compression.
        /// </summary>
        internal static string _dbCompress_BalloonTitle {
            get {
                return ResourceManager.GetString("_dbCompress_BalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to:.
        /// </summary>
        internal static string _dbConnectionDbFile {
            get {
                return ResourceManager.GetString("_dbConnectionDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to a Database file.
        /// </summary>
        internal static string _dbConnectionNoDbFile {
            get {
                return ResourceManager.GetString("_dbConnectionNoDbFile", resourceCulture);
            }
        }
    }
}
